### ISSUE TITLE
missing some modules

### ISSUE THREAD

**Issue by mrt-kousha** [nad2000/Flask-Timesheets#1]
Hi bro

I was going to implement this project, but some modules are not available like `flask_timesheet` thus i can't import `db` or `app`.

Thanks for this helpful project

**Comment by nad2000** [comment]
Thx for reaching out. I will take a look into it and come back shortly...

**Comment by mrt-kousha** [comment]
Thanks alot.

**Comment by nad2000** [comment]
Wich Python version are running?

**Comment by mrt-kousha** [comment]
I've been tested both Python version 2.7 and Python version 3.6, And I got this error:
`Traceback (most recent call last):`
`  File "manage.py", line 8, in <module>`
`    from flask_timesheets import app`
`ImportError: No module named flask_timesheets`
I think, the problem isn't with the Python's version.

**Comment by josephonyemakonor** [comment]
Hello,

Please this app doesn't load, cant import model, no FLASK_APP = time_sheet doesn't load

**Comment by nad2000** [comment]
@codecassava, as far as I remember it doesn't feature the module layout. It was developed before flask had FLASK_APP...

**Comment by SHERWAN-MULLA** [comment]
Error: While importing 'time_sheets', an ImportError was raised:

Traceback (most recent call last):
  File "d:\ft\lib\site-packages\flask\cli.py", line 218, in locate_app
    __import__(module_name)
  File "D:\ft\Flask-Timesheets\time_sheets\__init__.py", line 2, in <module>
    from flask_security import current_user
ModuleNotFoundError: No module named 'flask_security'
